applicationName: ware-fastapi-app
deploymentGroupName: ware-fastapi-group
revision:
  revisionType: AppSpecContent
  appSpecContent:
    content: |
      version: 0.0
      Resources:
        - TargetService:
            Type: AWS::ECS::Service
            Properties:
              TaskDefinition: arn:aws:ecs:eu-north-1:386056457794:task-definition/ware-fastapi-task:1
              LoadBalancerInfo:
                ContainerName: "ware-fastapi-container"
                ContainerPort: 8000

