applicationName: ware-fastapi-app
deploymentGroupName: ware-fastapi-group
revision:
  revisionType: AppSpecContent
  appSpecContent:
    content: |
      version: 0.0
      Resources:
        - TargetService:
            Type: AWS::ECS::Service
            Properties:
              TaskDefinition: "task-definition.json"
              LoadBalancerInfo:
                ContainerName: "ware-fastapi-container"
                ContainerPort: 8000

