name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-13-60-59-122.eu-north-1.compute.amazonaws.com << 'EOF'
            cd /home/ubuntu/ware-fastapi
            git pull origin main
            docker compose up -d --build
            # If using a virtual environment, restart the application
            # source venv/bin/activate
            # Restart services if needed
            # sudo systemctl restart your-app.service
          EOF